### ISSUE TITLE
Support for Visual Studio 2022?

### ISSUE THREAD

**Issue by jessehouwing** [mrlacey/ShowKeys#12]
I'm looking for this extension with VS2022 support. Not sure if there is an alternative you're aware of or whether this extension could be easily extended to support VS2022...

**Comment by mrlacey** [comment]
I have no plans for adding support for VS2022. I'm using [Carnac Keys](http://carnackeys.com/) (also on GitHub https://github.com/Code52/carnac) to do a similar thing but in a broader way.

Benefits:
- Not just limited to Visual Studio
- Better support for custom functionality.
